version: "3.8"
# NGC-DEPRECATION IMMUNITY
# This compose file is NGC-independent:
# - Uses NVIDIA_API_KEY (replaces legacy keys)
# - No hard dependency on vendor-specific registries
# - Cloud-first strategy via NVIDIA Build platform remains primary

services:
  embedder:
    # Default to a non-NGC local/registry image; override via EMBED_IMAGE
    image: ${EMBED_IMAGE:-localhost/nim/nv-embedqa-e5-v5:latest}
    container_name: embed-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - EMBED_MODEL=nv-embedqa-e5-v5
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8501/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["embed"]

  reranker:
    # Default to a non-NGC local/registry image; override via RERANK_IMAGE
    image: ${RERANK_IMAGE:-localhost/nim/llama-3_2-nemoretriever-500m-rerank-v2:latest}
    container_name: rerank-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - RERANK_MODEL=llama-3_2-nemoretriever-500m-rerank-v2
    ports:
      - "8502:8502"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8502/health"]
    
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["rerank"]

  extraction:
    # Default to a non-NGC local/registry image; override via EXTRACT_IMAGE
    image: ${EXTRACT_IMAGE:-localhost/nim/nv-ingest:latest}
    container_name: extract-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    ports:
      - "8503:8503"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8503/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["extraction"]
