version: "3.8"
# NGC-DEPRECATION IMMUNITY
# This compose file is NGC-independent:
# - Uses NVIDIA_API_KEY (not NGC_API_KEY)
# - No hard dependency on nvcr.io registry
# - Cloud-first strategy via NVIDIA Build platform remains primary

services:
  embedder:
    image: ${EMBED_IMAGE:-nvidia/nv-embedqa-e5-v5:latest}
    container_name: embed-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - EMBED_MODEL=nv-embedqa-e5-v5
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8501/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["embed"]

  reranker:
    image: ${RERANK_IMAGE:-nvidia/llama-3_2-nemoretriever-500m-rerank-v2:latest}
    container_name: rerank-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - RERANK_MODEL=llama-3_2-nemoretriever-500m-rerank-v2
    ports:
      - "8502:8502"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8502/health"]
    
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["rerank"]

  extraction:
    # NOTE: Provide a NGC-independent image via EXTRACT_IMAGE for self-hosted deployments
    # Example: export EXTRACT_IMAGE=myregistry.example.com/nv-ingest:latest
    image: ${EXTRACT_IMAGE:-nvidia/nv-ingest:latest}
    container_name: extract-nim
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    ports:
      - "8503:8503"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H 'Authorization: Bearer $NVIDIA_API_KEY' http://localhost:8503/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["extraction"]
