# MkDocs Configuration for Pharmaceutical RAG Template
# Documentation: https://www.mkdocs.org/user-guide/configuration/

site_name: Pharmaceutical RAG Template - NVIDIA NeMo Retriever
site_description: Comprehensive documentation for pharmaceutical RAG system using NVIDIA NeMo Retriever
site_author: Architecture Team
repo_url: https://github.com/hendrixmm/RAG-Template-for-NVIDIA-nemoretriever
repo_name: RAG-Template-for-NVIDIA-nemoretriever
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant      # Instant loading
    - navigation.tracking     # URL updates with scroll
    - navigation.tabs         # Top-level sections as tabs
    - navigation.sections     # Sections in navigation
    - navigation.expand       # Expand sections by default
    - navigation.top          # Back to top button
    - search.suggest          # Search suggestions
    - search.highlight        # Highlight search terms
    - content.code.copy       # Copy button for code blocks
    - content.code.annotate   # Annotations in code blocks
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - Installation: INSTALLATION.md
      - Quick Start: QUICK_START.md
      - Configuration: CONFIGURATION.md
  - Documentation:
      - API Reference: API_REFERENCE.md
      - Examples: EXAMPLES.md
      - Benchmarks: BENCHMARKS.md
      - Architecture Decision Records:
          - Overview: adr/README.md
          - ADR-0001 Use NeMo Retriever: adr/0001-use-nemo-retriever.md
          - Template: adr/template.md
  - Operations:
      - Troubleshooting Guide: TROUBLESHOOTING_GUIDE.md
      - Monitoring: MONITORING.md
      - Deployment: DEPLOYMENT.md
  - Development:
      - Contributing: CONTRIBUTING.md
      - Development Setup: DEVELOPMENT.md
      - Testing: TESTING.md
  - Resources:
      - Changelog: CHANGELOG.md
      - Roadmap: ROADMAP.md
      - Support: SUPPORT.md

# Extra configuration
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hendrixmm/RAG-Template-for-NVIDIA-nemoretriever
      name: GitHub Repository
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback! Help us improve by opening an issue.

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Validation and build settings
strict: true              # Fail build on warnings
use_directory_urls: true  # Use directory URLs (prettier)

# Copyright
copyright: Copyright &copy; 2025 Pharmaceutical RAG Template Contributors
