name: Docs Checks

on:
  pull_request:
    paths:
      - "**/*.md"
      - "scripts/docs_*.py"
      - "Makefile"
  workflow_dispatch: {}

jobs:
  docs-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: TOC drift check
        run: |
          python scripts/docs_toc_generator.py README.md --check --quiet
          find docs -name '*.md' -exec python scripts/docs_toc_generator.py {} --check --quiet \;

      - name: Link check (internal)
        run: |
          python scripts/docs_linkcheck.py --skip-external --exclude tests/ --exclude easyapi-pubmed-optimization-guide.md --exclude easyapi-pubmed-integration.md

      - name: Metadata validation (docs/)
        run: |
          python scripts/docs_metadata_validator.py --path docs/
