name: NGC Dependency Audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ripgrep (rg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Run NGC audit script
        run: |
          bash scripts/audit_ngc_dependencies.sh -v
