name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run-integration:
        description: "Run integration tests against real NeMo APIs"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]
      test-real-pdf-path:
        description: "Absolute path to a real PDF accessible to the runner"
        required: false
        default: ""

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest python-dotenv
      - name: Run mocked unit tests (no network)
        run: |
          pytest -q tests -k "not integration"

  integration:
    if: ${{ github.event.inputs.run-integration == 'true' }}
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies for integration
        run: |
          python -m pip install --upgrade pip
          pip install pytest python-dotenv aiohttp aiofiles
      - name: Run real API integration test
        env:
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
          TEST_REAL_PDF_PATH: ${{ github.event.inputs.test-real-pdf-path }}
        run: |
          pytest -q -m integration tests/test_nemo_extraction_integration.py

